server {
    listen 80;
    server_name _;

    client_max_body_size 10m;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/backend/public;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param PATH_INFO "";
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_param REQUEST_METHOD $request_method;
        fastcgi_pass app:9000;
    }

    location /storage/ {
        alias /var/www/backend/storage/app/public/;
        access_log off;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
