import { UserRole, UserStatus, TaskStatus, TaskPriority, WorkflowStepStepType, WorkflowStatus, ActivityItemType, NotificationType, EmailTemplateTrigger, SystemSettingsDefaultLanguage } from "@workspace/api-client-react";
import type { User, Team, Workflow, TaskDetail, Notification, EmailTemplate, ActivityItem, SystemSettings } from "@workspace/api-client-react";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Admin User",
    email: "admin@company.com",
    role: UserRole.admin,
    teamId: "team-1",
    teamName: "Engineering",
    avatar: "https://i.pravatar.cc/150?u=admin@company.com",
    status: UserStatus.active,
    createdAt: new Date().toISOString(),
    lastLogin: new Date().toISOString(),
  },
  {
    id: "user-2",
    name: "Regular User",
    email: "user@company.com",
    role: UserRole.user,
    teamId: "team-2",
    teamName: "Design",
    avatar: "https://i.pravatar.cc/150?u=user@company.com",
    status: UserStatus.active,
    createdAt: new Date().toISOString(),
    lastLogin: new Date().toISOString(),
  },
  {
    id: "user-3",
    name: "Jane Smith",
    email: "jane@company.com",
    role: UserRole.user,
    teamId: "team-1",
    teamName: "Engineering",
    avatar: "https://i.pravatar.cc/150?u=jane@company.com",
    status: UserStatus.active,
    createdAt: new Date().toISOString(),
  },
  {
    id: "user-4",
    name: "Bob Jones",
    email: "bob@company.com",
    role: UserRole.user,
    teamId: "team-3",
    teamName: "Product",
    status: UserStatus.active,
    createdAt: new Date().toISOString(),
  },
];

export const mockTeams: Team[] = [
  {
    id: "team-1",
    name: "Engineering",
    description: "Core engineering team",
    color: "#3b82f6",
    memberCount: 2,
    taskCount: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "team-2",
    name: "Design",
    description: "Product design team",
    color: "#ec4899",
    memberCount: 1,
    taskCount: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: "team-3",
    name: "Product",
    description: "Product management",
    color: "#8b5cf6",
    memberCount: 1,
    taskCount: 8,
    createdAt: new Date().toISOString(),
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: "wf-1",
    name: "Software Release",
    description: "Standard software deployment process",
    status: WorkflowStatus.active,
    taskCount: 12,
    createdAt: new Date().toISOString(),
    steps: [
      {
        id: "step-1",
        name: "Code Review",
        description: "Review pull request",
        order: 1,
        teamId: "team-1",
        teamName: "Engineering",
        stepType: WorkflowStepStepType.review,
        required: true,
      },
      {
        id: "step-2",
        name: "QA Testing",
        description: "Verify functionality",
        order: 2,
        teamId: "team-1",
        teamName: "Engineering",
        stepType: WorkflowStepStepType.action,
        required: true,
      },
      {
        id: "step-3",
        name: "Product Approval",
        description: "Final sign-off",
        order: 3,
        teamId: "team-3",
        teamName: "Product",
        stepType: WorkflowStepStepType.approval,
        required: true,
      },
      {
        id: "step-4",
        name: "Deploy",
        description: "Deploy to production",
        order: 4,
        teamId: "team-1",
        teamName: "Engineering",
        stepType: WorkflowStepStepType.action,
        required: true,
      }
    ],
  },
  {
    id: "wf-2",
    name: "New Feature Design",
    description: "Design process for new features",
    status: WorkflowStatus.active,
    taskCount: 5,
    createdAt: new Date().toISOString(),
    steps: [
      {
        id: "step-2-1",
        name: "Wireframing",
        order: 1,
        teamId: "team-2",
        teamName: "Design",
        stepType: WorkflowStepStepType.action,
        required: true,
      },
      {
        id: "step-2-2",
        name: "Design Review",
        order: 2,
        teamId: "team-3",
        teamName: "Product",
        stepType: WorkflowStepStepType.review,
        required: true,
      },
      {
        id: "step-2-3",
        name: "High Fidelity Design",
        order: 3,
        teamId: "team-2",
        teamName: "Design",
        stepType: WorkflowStepStepType.action,
        required: true,
      },
      {
        id: "step-2-4",
        name: "Final Approval",
        order: 4,
        teamId: "team-3",
        teamName: "Product",
        stepType: WorkflowStepStepType.approval,
        required: true,
      }
    ],
  }
];

export const mockTasks: TaskDetail[] = [
  {
    id: "task-1",
    title: "Deploy Auth Service v2",
    description: "Update the auth service to use new JWT tokens",
    status: TaskStatus.in_progress,
    priority: TaskPriority.high,
    workflowId: "wf-1",
    workflowName: "Software Release",
    currentStepId: "step-2",
    currentStepName: "QA Testing",
    currentStepIndex: 1,
    totalSteps: 4,
    assignedTeamId: "team-1",
    assignedTeamName: "Engineering",
    assignedUserId: "user-1",
    assignedUserName: "Admin User",
    createdById: "user-3",
    createdByName: "Jane Smith",
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    isOverdue: false,
    commentCount: 2,
    workflow: mockWorkflows[0],
    comments: [
      {
        id: "c-1",
        taskId: "task-1",
        userId: "user-3",
        userName: "Jane Smith",
        content: "I have finished the code review, looks good.",
        isInternal: false,
        createdAt: new Date(Date.now() - 40000000).toISOString(),
      },
      {
        id: "c-2",
        taskId: "task-1",
        userId: "user-1",
        userName: "Admin User",
        content: "Starting QA testing now.",
        isInternal: false,
        createdAt: new Date(Date.now() - 3600000).toISOString(),
      }
    ],
    internalNotes: [
      {
        id: "in-1",
        taskId: "task-1",
        userId: "user-1",
        userName: "Admin User",
        content: "Note: We need to check backward compatibility.",
        isInternal: true,
        createdAt: new Date(Date.now() - 2000000).toISOString(),
      }
    ],
    activityLog: [
      {
        id: "al-1",
        type: ActivityItemType.task_created,
        userId: "user-3",
        userName: "Jane Smith",
        taskId: "task-1",
        taskTitle: "Deploy Auth Service v2",
        description: "created the task",
        createdAt: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: "al-2",
        type: ActivityItemType.step_completed,
        userId: "user-3",
        userName: "Jane Smith",
        taskId: "task-1",
        taskTitle: "Deploy Auth Service v2",
        description: "completed step: Code Review",
        createdAt: new Date(Date.now() - 40000000).toISOString(),
      }
    ],
    attachments: [
      {
        id: "a-1",
        taskId: "task-1",
        fileName: "auth_spec.pdf",
        fileSize: 1024000,
        fileType: "application/pdf",
        url: "#",
        uploadedByName: "Jane Smith",
        createdAt: new Date(Date.now() - 86000000).toISOString(),
      }
    ]
  },
  {
    id: "task-2",
    title: "Design Dashboard UI",
    description: "Create wireframes for the new analytics dashboard",
    status: TaskStatus.open,
    priority: TaskPriority.medium,
    workflowId: "wf-2",
    workflowName: "New Feature Design",
    currentStepId: "step-2-1",
    currentStepName: "Wireframing",
    currentStepIndex: 0,
    totalSteps: 4,
    assignedTeamId: "team-2",
    assignedTeamName: "Design",
    assignedUserId: "user-2",
    assignedUserName: "Regular User",
    createdById: "user-4",
    createdByName: "Bob Jones",
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    createdAt: new Date(Date.now() - 100000).toISOString(),
    isOverdue: false,
    commentCount: 0,
    workflow: mockWorkflows[1],
    comments: [],
    internalNotes: [],
    activityLog: [],
    attachments: []
  },
  {
    id: "task-3",
    title: "Fix Payment Gateway Bug",
    description: "Payments are failing sporadically with timeout errors",
    status: TaskStatus.open,
    priority: TaskPriority.urgent,
    workflowId: "wf-1",
    workflowName: "Software Release",
    currentStepId: "step-1",
    currentStepName: "Code Review",
    currentStepIndex: 0,
    totalSteps: 4,
    assignedTeamId: "team-1",
    assignedTeamName: "Engineering",
    createdById: "user-1",
    createdByName: "Admin User",
    dueDate: new Date(Date.now() - 86400000).toISOString(),
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    isOverdue: true,
    commentCount: 0,
    workflow: mockWorkflows[0],
    comments: [],
    internalNotes: [],
    activityLog: [],
    attachments: []
  },
  {
    id: "task-4",
    title: "Update User Settings Page",
    description: "Add language preferences to settings",
    status: TaskStatus.completed,
    priority: TaskPriority.low,
    workflowId: "wf-1",
    workflowName: "Software Release",
    currentStepId: "step-4",
    currentStepName: "Deploy",
    currentStepIndex: 3,
    totalSteps: 4,
    assignedTeamId: "team-1",
    assignedTeamName: "Engineering",
    assignedUserId: "user-1",
    assignedUserName: "Admin User",
    createdById: "user-3",
    createdByName: "Jane Smith",
    dueDate: new Date(Date.now() + 86400000 * 10).toISOString(),
    createdAt: new Date(Date.now() - 500000000).toISOString(),
    isOverdue: false,
    commentCount: 1,
    workflow: mockWorkflows[0],
    comments: [],
    internalNotes: [],
    activityLog: [],
    attachments: []
  },
  {
    id: "task-5",
    title: "App Icon Redesign",
    description: "Update the mobile app icon for the summer release",
    status: TaskStatus.on_hold,
    priority: TaskPriority.medium,
    workflowId: "wf-2",
    workflowName: "New Feature Design",
    currentStepId: "step-2-3",
    currentStepName: "High Fidelity Design",
    currentStepIndex: 2,
    totalSteps: 4,
    assignedTeamId: "team-2",
    assignedTeamName: "Design",
    assignedUserId: "user-2",
    assignedUserName: "Regular User",
    createdById: "user-4",
    createdByName: "Bob Jones",
    dueDate: new Date(Date.now() + 86400000 * 15).toISOString(),
    createdAt: new Date(Date.now() - 800000000).toISOString(),
    isOverdue: false,
    commentCount: 0,
    workflow: mockWorkflows[1],
    comments: [],
    internalNotes: [],
    activityLog: [],
    attachments: []
  }
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    type: NotificationType.assigned,
    title: "Task Assigned",
    message: "You have been assigned to 'Deploy Auth Service v2'",
    taskId: "task-1",
    taskTitle: "Deploy Auth Service v2",
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "notif-2",
    userId: "user-1",
    type: NotificationType.overdue,
    title: "Task Overdue",
    message: "'Fix Payment Gateway Bug' is overdue!",
    taskId: "task-3",
    taskTitle: "Fix Payment Gateway Bug",
    isRead: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "notif-3",
    userId: "user-2",
    type: NotificationType.assigned,
    title: "Task Assigned",
    message: "You have been assigned to 'Design Dashboard UI'",
    taskId: "task-2",
    taskTitle: "Design Dashboard UI",
    isRead: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  }
];

export const mockEmailTemplates: EmailTemplate[] = [
  {
    id: "et-1",
    name: "Task Assigned",
    subject: "You have been assigned to a new task: {{task.title}}",
    body: "Hello {{user.name}},\n\nYou have been assigned to task {{task.title}}.\n\nPlease review the task details.\n\nThanks,\nFlowDesk",
    trigger: EmailTemplateTrigger.task_assigned,
    variables: ["user.name", "task.title", "task.id"],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "et-2",
    name: "Task Overdue",
    subject: "Task Overdue: {{task.title}}",
    body: "Hello {{user.name}},\n\nThe task {{task.title}} is now overdue.\n\nPlease complete it as soon as possible.\n\nThanks,\nFlowDesk",
    trigger: EmailTemplateTrigger.task_overdue,
    variables: ["user.name", "task.title", "task.dueDate"],
    isActive: true,
    createdAt: new Date().toISOString(),
  }
];

export const mockSettings: SystemSettings = {
  companyName: "Acme Corp",
  defaultLanguage: SystemSettingsDefaultLanguage.en,
  emailEnabled: true,
  primaryColor: "#3b82f6",
  allowRegistration: false,
  requireEmailVerification: false
};
